# Étape 1 : image de base
FROM ubuntu:latest

# Étape 2 : mise à jour des paquets
RUN apt-get update

# Étape 3 : mise à niveau des paquets
RUN apt-get upgrade -y

# Étape 4 : commande à exécuter au lancement du conteneur
CMD echo "Hello, World!"
