version: '3'
services:
  back-end:
    build: ./back-end
    expose:
      - "5252"

  front-end:
    build: ./front-end
    expose:
      - "80"
    depends_on:
      - back-end

  proxy:
    build: ./proxy
    ports:
      - "8080:80"
    depends_on:
      - front-end
      - back-end
